# -*- coding: utf-8 -*-
"""Gráfico com Plotly.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LEqNCYOdh-_tq8SjawnSKe_zVXjpwWOO

Pip install
"""

!pip install --upgrade pip setuptools wheel

!pip install plotly --prefer-binary

!pip install kaleido --prefer-binary

!pip freeze > requirements.txt

"""Gráfico de Linha com Plotly"""

import plotly.express as px
import pandas as pd

indices = [1, 2, 3, 4]
amostras = [[1, 4, 2, 3], [2, 8, 4, 6], [4, 16, 8, 12]]

fig = px.line(x=indices, y=amostras, title='Titulo do Gráfico',
              labels=dict(value='Label Y', x='Label X', variable='Amostras')
             )
fig.data[0].name = 'Amostra A'
fig.data[1].name = 'Amostra B'
fig.data[2].name = 'Amostra C'

#fig.update_layout(showlegend=False) # tira a lengenda ao lado do gráfico


fig.show()

"""Gráfico de Barra com Plotly"""

import plotly.express as px

frutas = ['Laranja', 'Melancia', 'Manga', 'Jaca']
quantidades = [60, 100, 85, 30]

fig = px.bar(x=frutas, y=quantidades, title='Titulo do Gráfico', color=frutas,
             labels=dict(y='Label Y', x='Label X', color='Frutas'))

fig.show()

import plotly.express as px
import numpy as np

pesquisa = np.random.normal(170, 10, 250)

fig = px.histogram(pesquisa, nbins=8, title='Titulo do Gráfico')

fig.update_layout(showlegend=False) # tira a lengenda ao lado do gráfico

fig.update_xaxes(title='Label X')
fig.update_yaxes(title='Label Y')

fig.update_traces(marker_line_width=0.5, marker_line_color='#ffffff')

fig.show()

"""Gráfico de Pizza com Plotly"""

import plotly.express as px
import pandas as pd

dados = {'frutas': ['Laranja', 'Melancia', 'Manga', 'Jaca'],
         'porcentagem': [15, 30, 45, 10]
        }
df = pd.DataFrame(data=dados)

fig = px.pie(df, values='porcentagem', names='frutas')

#fig.update_layout(showlegend=False) # tira a lengenda ao lado do gráfico

fig.update_traces(textinfo='percent+label')

fig.update_layout(hovermode=False)# passa o mause encima a apresenta a porcentagem

fig.show()

df

"""Salvando a imagem do gráfico com Plotly"""

import plotly.express as px
import pandas as pd
import plotly.io as io

dados = {'frutas': ['Laranja', 'Melancia', 'Manga', 'Jaca'],
         'porcentagem': [15, 30, 45, 10]
        }
df = pd.DataFrame(data=dados)

fig = px.pie(df, values='porcentagem', names='frutas')

#fig.update_layout(showlegend=False) # tira a lengenda ao lado do gráfico

fig.update_traces(textinfo='percent+label')

fig.update_layout(hovermode=False)# passa o mause encima a apresenta a porcentagem

#fig.show()

io.write_image(fig , 'grafico.png' )

#io.write_json()
#io.write_html()